# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8040
    servlet:
        context-path: /

# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

logging:
  level: info
  level.com.mvwchina: error
  path: logs/
  file: admin.log

